server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      # consul注册中心地址
      host: 140.210.221.183
      port: 8500
      discovery:
#        hostname: 140.210.221.183
        service-name: ${spring.application.name}


