server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          filters:
            - AddRequestParameter=X-Request-Id,1024
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
            - After=2023-01-03T16:10:17.412+08:00[Asia/Shanghai]
            - Cookie=username,zzyy
            - Header=X-Request-Id,\d+
            - Host=**.baidu.com
            - Method=GET
        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            Path=/payment/lb/** #断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka